---
# tasks file for packages
- name: Ensure system up to date
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install pip and basic build packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - make
      - gcc
    state: present
