---
- name: "Destroy all apps"
  hosts: docker
  become: true
  tasks:
    - name: "Get Services"
      delegate_to: localhost
      shell: ls apps
      register: dir_output
      changed_when: False
      failed_when: dir_output.stdout_lines == []

    - name: "Destroy service"
      with_items: "{{ dir_output.stdout_lines | list }}"
      include_role:
        name: destroy-compose
      vars:
        app_name: "{{ item }}"