---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.docker
  - name: cloudalchemy.grafana

collections:
  - name: community.docker
  - name: community.general
  - name: prometheus.prometheus
