---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.docker
  - name: cloudalchemy.node_exporter
  - name: cloudalchemy.grafana
  - name: cloudalchemy.prometheus

collections:
  - name: community.docker
  - name: community.general
