- hosts: docker
  become: true
  tasks:
    - name: Install node_exporter
      include_role:
        name: cloudalchemy.node_exporter

    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_daemon_options:
          metrics-addr: "0.0.0.0:9323"
          experimental: true

    - name: Install Pip3
      apt:
        update_cache: yes
        name: python3-pip
        state: latest
