- name: Setup monitoring server
  hosts: monitoring
  become: true
  roles:
    - cloudalchemy.prometheus
    - geerlingguy.docker

- name: Setup grafana
  hosts: monitoring
  become: true
  roles:
    - cloudalchemy.grafana
  vars:
    grafana_security:
      admin_user: admin
      # TODO
      admin_password: test
    grafana_datasources:
    - name: prometheus
      type: prometheus
      url: 'http://localhost:9090'
      basicAuth: false
    - name: loki
      type: loki
      url: 'http://localhost:3100'
      basicAuth: false

- name: Deploy monitoring stack
  hosts: monitoring
  become: true
  tasks:
  - name: Deploy Caddy and Loki
    include_role:
      name: docker-application
    vars:
      app_names:
        - monitoring
      app_state: deploy