- name: Setup monitoring server
  hosts: monitoring
  become: true
  tasks:

  - name: Install Pip
    ansible.builtin.apt:
      name: python3-pip
      state: present

  - name: Install docker
    ansible.builtin.include_role:
      name: geerlingguy.docker
    vars:
      docker_daemon_options:
        metrics-addr: "0.0.0.0:9323"
        experimental: true

  - name: Install prometheus
    ansible.builtin.include_role:
      name: cloudalchemy.prometheus
    vars:
      prometheus_config_file: apps/monitoring/prometheus.yml

  - name: Install node_exporter
    ansible.builtin.include_role:
      name: cloudalchemy.node_exporter

  - name: Deploy monitoring stack
    ansible.builtin.include_role:
      name: docker-application
    vars:
      app_names:
        - cadvisor
        - monitoring
      app_state: deploy

  - name: Setup grafana
    ansible.builtin.include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "{{ grafana_admin_pass }}"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          url: 'http://localhost:9090'
          basicAuth: false
        - name: loki
          type: loki
          url: 'http://localhost:3100'
          basicAuth: false
