---
- name: Setup Docker Applications
  hosts: docker
  become: true
  tasks:
    - name: Install node_exporter
      ansible.builtin.include_role:
        name: cloudalchemy.node_exporter

    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_daemon_options:
          metrics-addr: "0.0.0.0:9323"
          experimental: true

    - name: Install Pip3
      ansible.builtin.apt:
        update_cache: true
        name: python3-pip
        state: present
