---
# tasks file for packages
- name: Ensure system up to date
  apt:
    upgrade: yes
    update_cache: yes

- name: Install pip and basic build packages
  apt:
    name:
      - python3-pip
      - make
      - gcc
      - docker-ce
    state: latest

- name: Install Ansible
  pip:
    name:
      - ansible
    state: present

- name: Install community.general ansible galaxy
  community.general.ansible_galaxy_install:
    type: collection
    name: community.general

- name: Install community.docker ansible galaxy
  community.general.ansible_galaxy_install:
    type: collection
    name: community.docker

