version: "3.8"

networks:
  netstack:

services:
  loki:
    image: grafana/loki:2.5.0
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - netstack

  prometheus:
    image: prom/prometheus:latest
    restart: always
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - ${APP_CONFIG_DIR:?err}/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - netstack

  grafana:
    image: grafana/grafana:latest
    restart: always
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - "${APP_DATA_DIR:?err}/graphana:/var/lib/grafana"
    networks:
      - netstack
