version: '3.2'

services:
  app:
    build: ./nc-docker
    ports:
      - 9001:80
    restart: always
    volumes:
      - "${APP_DATA_DIR:?err}:/var/www/html"
    environment:
      SQLITE_DATABASE: nextcloud
      NEXTCLOUD_ADMIN_USER: "${nextcloud_admin_user:?err}"
      NEXTCLOUD_ADMIN_PASSWORD: "${nextcloud_admin_password:?err}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${nextcloud_trusted_domains:?err}"
      TRUSTED_PROXIES: "${trusted_proxies:?err}"
      OBJECTSTORE_S3_HOST: "${s3_url:?err}"
      OBJECTSTORE_S3_BUCKET: "${s3_bucket:?err}"
      OBJECTSTORE_S3_KEY: "${s3_key:?err}"
      OBJECTSTORE_S3_SECRET: "${s3_secret:?err}"
      OBJECTSTORE_S3_PORT: "${s3_port:?err}"
      OBJECTSTORE_S3_SSL: "false"
      OBJECTSTORE_S3_REGION: "{s3_region:?err}"
      OBJECTSTORE_S3_USEPATH_STYLE: "true"
      OBJECTSTORE_S3_AUTOCREATE: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.lan.jamsparrow.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
