---
# tasks file for deploy-compose
- name: Install required pip packages
  pip:
    name:
      - docker>=1.8.0
      - docker-compose>=1.7.0,<2.0.0
      - PyYaml>=3.11
    state: present

- name: Begin Destroy Compose
  vars:
    PWD: "{{ lookup('env', 'PWD') }}"
    config_dir: "/config/"
    app_config_dir: "/config/{{ app_name }}"
    data_dir: "/data/"
    app_data_dir: "/data/{{ app_name }}"
  block:
  - name: Clear app config directory
    ansible.builtin.file:
      path: "{{ app_config_dir }}"
      state: absent

  - name: Reinitialise app config directory
    ansible.builtin.file:
      path: "{{ app_config_dir }}"
      state: directory
      mode: '0755'

  - name: Copy over app files
    ansible.builtin.copy:
      src: "{{ PWD }}/apps/{{ app_name }}"
      decrypt: yes
      dest: "{{ config_dir }}"

  - name: Delete services
    community.docker.docker_compose:
      project_src: "{{ app_config_dir }}"
      project_name: "{{ app_name }}"
      remove_orphans: yes
      state: absent
    environment:
      APP_DATA_DIR: "{{ app_data_dir }}"
      APP_CONFIG_DIR: "{{ app_config_dir }}"


  - name: Delete volumes
    when: (delete_volumes is defined) and (delete_volumes == 'true')
    block:
    - name: Remove Docker volumes
      community.docker.docker_compose:
        project_src: "{{ app_config_dir }}"
        project_name: "{{ app_name }}"
        remove_volumes: yes
        state: absent
      environment:
        APP_DATA_DIR: "{{ app_data_dir }}"
        APP_CONFIG_DIR: "{{ app_config_dir }}"

    - name: Delete app data directory
      ansible.builtin.file:
        path: "{{ app_data_dir }}"
        state: absent

    - name: Delete app config directory
      ansible.builtin.file:
        path: "{{ app_config_dir }}"
        state: absent
