---
# tasks file for deploy-compose
- name: Install required pip packages
  pip:
    name:
      - docker>=1.8.0
      - docker-compose>=1.7.0,<2.0.0
      - PyYaml>=3.11
    state: present

- name: Begin Destroy Compose
  vars:
    PWD: "{{ lookup('env', 'PWD') }}"
  block:
  - name: Create tmp directory
    ansible.builtin.file:
      path: "/tmp/{{ app_name }}"
      state: directory
      mode: '0755'

  - name: Copy over compose file
    ansible.builtin.copy:
      src: "{{ PWD }}/apps/{{ app_name }}/docker-compose.yaml"
      dest: "/tmp/{{ app_name }}/docker-compose.yaml"

  - name: Check .env file exists
    delegate_to: localhost
    stat:
      path: "{{ PWD }}/apps/{{ app_name }}/.env"
    register: env_file

  - name: Copy over .env file
    ansible.builtin.copy:
      src: "{{ PWD }}/apps/{{ app_name }}/.env"
      dest: "/tmp/{{ app_name }}/.env"
      decrypt: yes
    when: env_file.stat.exists

  - name: Delete services
    community.docker.docker_compose:
      project_src: "/tmp/{{ app_name }}"
      project_name: "{{ app_name }}"
      state: absent

  - name: Delete volumes
    when: (delete_volumes is defined) and (delete_volumes == 'true')
    block:
    - name: Remove Docker volumes
      community.docker.docker_compose:
        project_src: "/tmp/{{ app_name }}"
        project_name: "{{ app_name }}"
        remove_volumes: yes
        state: absent

    - name: Delete app data directory
      ansible.builtin.file:
        path: "/data/{{ app_name }}"
        state: absent

  always:
  - name: Delete compose and env file
    ansible.builtin.file:
      path: "/tmp/{{ app_name }}"
      state: absent
