version: '3.8'
services:
  uptimekuma:
    image: louislam/uptime-kuma:1
    volumes:
      - "/${APP_DATA_DIR:?err}:/app/data"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptime.lan.jamochl.com`)"
      - "traefik.http.routers.uptimekuma.entrypoints=web"
      - "traefik.http.routers.uptimekuma.service=uptimekuma@docker"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
