---
# tasks file for deploy-compose
- name: Install required pip packages
  pip:
    name:
      - docker>=1.8.0
      - docker-compose>=1.7.0,<2.0.0
      - PyYaml>=3.11
    state: present

- name: Ensure config directory exists
  ansible.builtin.file:
    path: /config
    state: directory
    mode: '0755'

- name: Ensure data directory exists
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0755'

- name: Begin Compose
  vars:
    PWD: "{{ lookup('env', 'PWD') }}"
    config_dir: "/config/"
    app_config_dir: "/config/{{ app_name }}"
    data_dir: "/data/"
    app_data_dir: "/data/{{ app_name }}"
  block:
  - name: Clear app config directory
    ansible.builtin.file:
      path: "{{ app_config_dir }}"
      state: absent

  - name: Reinitialise app config directory
    ansible.builtin.file:
      path: "{{ app_config_dir }}"
      state: directory
      mode: '0755'

  - name: Copy over app files
    ansible.builtin.copy:
      src: "{{ PWD }}/apps/{{ app_name }}"
      decrypt: yes
      dest: "{{ config_dir }}"

  - name: Create and start services
    community.docker.docker_compose:
      project_src: "{{ app_config_dir }}"
      project_name: "{{ app_name }}"
      build: yes
      pull: yes
      remove_orphans: yes
      recreate: always
      state: present
    environment:
      APP_DATA_DIR: "{{ app_data_dir }}"
      APP_CONFIG_DIR: "{{ app_config_dir }}"