---
# tasks file for gocd
#
- name: Add gocd source
  ansible.builtin.apt_repository:
    repo: "deb https://download.gocd.org /"
    state: present
  tags: ntp

- name: Add gocd key
  ansible.builtin.apt_key:
    url: https://download.gocd.org/GOCD-GPG-KEY.asc
    state: present

- name: Cache Update
  ansible.builtin.apt:
    update_cache: true

- name: Install go-server and go-agent
  ansible.builtin.apt:
    name:
      - go-server
      - go-agent
    state: present

- name: Start go-server
  service:
    name: go-server
    state: started
    enabled: true

- name: Start go-agent
  service:
    name: go-agent
    state: started
    enabled: true
