---
# tasks file for gocd
#
- name: Add gocd source
  ansible.builtin.apt_repository:
    repo: "deb https://download.gocd.org /"
    state: present
  tags: ntp

- name: Add gocd key
  ansible.builtin.apt_key:
    url: https://download.gocd.org/GOCD-GPG-KEY.asc
    state: present

- name: Cache Update
  apt:
    update_cache: yes

- name: Install go-server and go-agent
  apt:
    name:
      - go-server
      - go-agent
    state: latest

- name: Start go-server
  service:
    name: go-server
    state: started
    enabled: yes

- name: Start go-agent
  service:
    name: go-agent
    state: started
    enabled: yes
