version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9003:80/tcp"
    environment:
      TZ: 'Australia/Melbourne'
      ServerIP: "${SERVER_IP:?err}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lan.jamochl.com`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.service=pihole@docker"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

    # Volumes store your data between container upgrades
    volumes:
      - '/${APP_DATA_DIR:?err}/etc-pihole/:/etc/pihole/'
      - '/${APP_DATA_DIR:?err}/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
