version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Australia/Melbourne'
      ServerIP: "pihole.lan.jamochl.com"

    # Volumes store your data between container upgrades
    volumes:
      - '/data/pihole/etc-pihole/:/etc/pihole/'
      - '/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
